#!/usr/bin/env node
// One-time SEO slug repair for EXISTING databases (local dev + remote prod that
// were seeded before the slugify fix). New seeds already produce clean slugs, so
// a fresh `seed` needs none of this — this only rewrites slugs already stored.
//
// It recomputes show/movie slugs with the improved slugify (apostrophes, quotes
// and acronym dots stripped) and only touches rows whose clean slug genuinely
// changed — unaffected rows (incl. their original -year/-id collision suffixes)
// are left exactly as-is. Writes scripts/reslug.sql and (with no --sql-only)
// applies it to the LOCAL D1. For remote:
//   wrangler d1 execute tvnightly --remote --file=scripts/reslug.sql
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const ROOT = "/Users/ghost/Documents/tvnightly";
const sqlOnly = process.argv.includes("--sql-only");

// SAME logic as src/lib/format.ts slugifyName + the seed scripts.
const slugify = (name) =>
  name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/&/g, " and ")
    .replace(/['‘’"“”.]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const dbPath = execSync(
  `ls -S ${ROOT}/.wrangler/state/v3/d1/miniflare-D1DatabaseObject/*.sqlite | head -1`,
  { shell: "/bin/zsh", encoding: "utf8" },
).trim();
const query = (sql) =>
  JSON.parse(execSync(`sqlite3 "${dbPath}" ".mode json" ${JSON.stringify(sql)}`, { encoding: "utf8" }).trim() || "[]");

const sqlEsc = (s) => s.replace(/'/g, "''");

// ---- shows: base = slugify(name); collide -> -year -> -id ----
const shows = query("SELECT id, name, premiered, slug FROM shows ORDER BY id");
const showUsed = new Set(shows.map((s) => s.slug));
const showChanges = [];
for (const s of shows) {
  const wanted = slugify(s.name);
  if (!wanted || wanted === s.slug) continue;
  showUsed.delete(s.slug);
  const year = s.premiered ? String(s.premiered).slice(0, 4) : "";
  let final = wanted;
  if (showUsed.has(final) && year) final = `${wanted}-${year}`;
  if (showUsed.has(final)) final = `${wanted}-${s.id}`;
  showUsed.add(final);
  if (final !== s.slug) showChanges.push({ id: s.id, old: s.slug, new: final });
}

// ---- movies: base = slugify(title)[-year]; collide -> -imdb_id ----
const movies = query("SELECT imdb_id, title, year, slug FROM movies ORDER BY imdb_id");
const movieUsed = new Set(movies.map((m) => m.slug));
const movieChanges = [];
for (const m of movies) {
  const base = m.year ? `${slugify(m.title)}-${m.year}` : slugify(m.title);
  if (!base || base === m.slug) continue;
  movieUsed.delete(m.slug);
  let final = base;
  if (movieUsed.has(final)) final = `${base}-${m.imdb_id}`;
  movieUsed.add(final);
  if (final !== m.slug) movieChanges.push({ imdb_id: m.imdb_id, old: m.slug, new: final });
}

// collision sanity: every new slug must be unique within its table's full set
const dupCheck = (used, label) => {
  if (used.size !== new Set([...used]).size) console.warn(`!! ${label} slug collision detected`);
};
dupCheck(showUsed, "shows");
dupCheck(movieUsed, "movies");

console.log(`shows: ${showChanges.length} slugs to fix`);
showChanges.slice(0, 30).forEach((c) => console.log(`  ${c.old}  ->  ${c.new}`));
console.log(`movies: ${movieChanges.length} slugs to fix`);
movieChanges.slice(0, 30).forEach((c) => console.log(`  ${c.old}  ->  ${c.new}`));

// ---- emit SQL: park changed rows at a free temp slug, then set finals ----
const lines = ["-- SEO slug repair (generated by scripts/reslug.mjs)", "BEGIN TRANSACTION;"];
if (showChanges.length) {
  lines.push("-- shows: park then rename");
  for (const c of showChanges) lines.push(`UPDATE shows SET slug = '__reslug_' || id WHERE id = ${c.id};`);
  for (const c of showChanges) lines.push(`UPDATE shows SET slug = '${sqlEsc(c.new)}' WHERE id = ${c.id};`);
}
if (movieChanges.length) {
  lines.push("-- movies: park then rename");
  for (const c of movieChanges) lines.push(`UPDATE movies SET slug = '__reslug_' || rowid WHERE imdb_id = '${sqlEsc(c.imdb_id)}';`);
  for (const c of movieChanges) lines.push(`UPDATE movies SET slug = '${sqlEsc(c.new)}' WHERE imdb_id = '${sqlEsc(c.imdb_id)}';`);
}
lines.push("COMMIT;", "");
const sql = lines.join("\n");
writeFileSync(`${ROOT}/scripts/reslug.sql`, sql);
console.log(`\nwrote scripts/reslug.sql (${showChanges.length + movieChanges.length} slugs)`);

if (!sqlOnly && showChanges.length + movieChanges.length) {
  execSync(`sqlite3 "${dbPath}" < ${ROOT}/scripts/reslug.sql`, { stdio: "inherit" });
  console.log("applied to LOCAL D1. Remote: wrangler d1 execute tvnightly --remote --file=scripts/reslug.sql");
}
